### ISSUE TITLE
wait module3  and module4

### ISSUE THREAD

**Issue by nolotus** [joehand/dat-examples#1]

**Comment by joehand** [comment]
Thanks, @nolotus. Those are coming soon! If you'd be interested in writing them, I'd welcome a PR. You can see how it may work by looking at the [dat-js](https://github.com/joehand/dat-js/blob/master/index.js#L85) module share function.

If you want to get notified about changes, you can use the "watch" button on github (top right). That will send you notifications when anything changes in the repository. That is usually better than opening a non-specific issue.
